### ISSUE TITLE
Comments diappear when loading / writing with `round_trip_dump`, `round_trip_load`

### ISSUE THREAD

**Issue by leilakanync** [pycontribs/ruyaml#115]
When loading / writing yaml with `round_trip_load` and `round_trip_dump`, comments surrounded by empty lines are not kept.

Example:

```yaml
test: test

# This is a comment

testend: testend
```
