### ISSUE TITLE
dump generates corrupt YAML

### ISSUE THREAD

**Issue by Meisterschueler** [pycontribs/ruyaml#118]
input.yaml
```
- id: BLABLA
  title: Notsoimportant
  requirements:
    - id: BLUBB
      description: |

        After one blank line we
        see some text here
```

output.yaml
```
- id: BLABLA
  title: Notsoimportant
  requirements:
    - id: BLUBB
      description: |4     # NOW THIS LINE IS INVALID YAML

        After one blank line we
        see some text here
```

myscript.py
```
from ruyaml import YAML, RoundTripRepresenter

def repr_str(dumper: RoundTripRepresenter, data:str):
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    else:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data)

yaml = YAML()
yaml.indent(mapping=2, sequence=4, offset=2)
yaml.representer.add_representer(str, repr_str)

with open("input.yaml", "r", encoding='utf-8') as file:
    data = yaml.load(file)

with open("output.yaml", "w", encoding='utf-8') as file:
    yaml.dump(data, file)


```
