### ISSUE TITLE
Dumper can generate bad YAML

### ISSUE THREAD

**Issue by archoversight** [pycontribs/ruyaml#28]
Hello,

I am using the old upstream project with a pre-commit hook: https://github.com/archoversight/pre-commit-hook-yamlfmt/tree/feature/explicit_end

However when I use the following configuration:

```
        yaml.indent(
            mapping=2,
            sequence=2,
            offset=2,
            )
```

Which I would hope would format the following:

```
---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.2.0
    hooks:
      - id: no-commit-to-branch
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/archoversight/pre-commit-hook-yamlfmt.git
    rev: 0.1.0-explicit
    hooks:
      - id: yamlfmt
        args: [--mapping, '4', --sequence, '4', --offset, '2', --explicit_end, --explicit_start]
...
```

As:

```
---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.2.0
    hooks:
      - id: no-commit-to-branch
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/archoversight/pre-commit-hook-yamlfmt.git
    rev: 0.1.0-explicit
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '2', --offset, '2', --explicit_end, --explicit_start]
...
```

However instead it formats it as follows:

```
---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v3.2.0
  hooks:
    - id: no-commit-to-branch
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace

  - repo: https://github.com/archoversight/pre-commit-hook-yamlfmt.git
  rev: 0.1.0-explicit
  hooks:
    - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '2', --explicit_end, --explicit_start]
...
```

For some reason it fails to take into account the fact that there is already an offset from the `-` before printing the next mapping.

Setting the sequence to `4` does seem to solve the problem, but it feels weird that this would be required.
