### ISSUE TITLE
unexpected overlap in comment with round_trip_load()

### ISSUE THREAD

**Issue by skhomuti** [pycontribs/ruyaml#46]
ruyaml.round_trip_load causes following error, but yaml hasn't contain any comments
```
NotImplementedError: overlap in comment [None, [CommentToken('\n', line: 2, col: 0)]] [None, [CommentToken('\n', line: 4, col: 0)]]
```
```
- config:
      key: {default: 123}

-

    config: 123
```
load() and safe_load() works fine
